Repository jeong7231/intel7_final_team6, pull requests merged in 2025-10, with the labels that each got.

#18 스티커 구분 AI에서 버그 수정본
  jetson_AI/debug_live_new.py
Labels: 버그, SW

#19 OpenCV 개선 및 Cpu, Gpu 성능테스트
  jetson_AI/debug_live_new.py
Labels: 기능 구현, SW

#27 컨베이어 역방향 동작 테스트
  firmware/arduino/L298N/L298N.ino
Labels: 기능 구현, HW, FW
